title: Chenghao Gao's Homepage
page-top-title: Chenghao Gao
top-section-bg-text: Computer Science
home-subtitle: Chenghao Gao&ensp;|&ensp;高诚浩
copyright-text: '&copy; Chenghao Gao 2023-2024. All Rights Reserved.'
